### ISSUE TITLE
delete sessions - modify to support safe mode in mysql

### ISSUE THREAD

**Issue by pateljatin** [nlf/connect-mysql#26]
Hi,

We should update the DELETE sessions query so that it works for mysql when set it to safe mode.
This is just an fyi for those folks running in to a similar problem...
something like this would do it:

```
'DELETE FROM `' + TableName + '` WHERE `sid` != 0 and `expires` > 0 and `expires` < UNIX_TIMESTAMP()';
```

Thanks,
Jatin

**Comment by jas-** [comment]
This has been addressed in `v2.1.6’`
