### ISSUE TITLE
Call for new maintainer

### ISSUE THREAD

**Issue by nlf** [nlf/connect-mysql#27]
I don't use this module any more, so it's grown quite stale.. I've tried to continue merging pull requests, but I haven't really been paying any attention to it.

Anyone that would like to take over as the maintainer, let me know here and I'd be happy to add you to the repo and on npm.

**Comment by jas-** [comment]
The `express-mysql-session` middleware doesn't handle encrypted session data as recommended by [OWASP session management](https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Session_ID_Content_.28or_Value.29).

I can take it over if you like @nlf, didn't realize you had stopped maintaining it but just pushed a new [pull request](https://github.com/nlf/connect-mysql/pull/32).

**Comment by nlf** [comment]
@jas- all yours, I’ll add you in the relevant places. What’s your npm username?

**Comment by nlf** [comment]
nevermind, i see by the avatar it's the same as github, you're added. enjoy :)

**Comment by jas-** [comment]
Oh yeah, npm is the same as here. Thanks for the doing the heavy lifting. I will get started on some dependency updates first.
