### ISSUE TITLE
Does not work with Sailsjs

### ISSUE THREAD

**Issue by sahanDissanayake** [nlf/connect-mysql#28]

**Comment by jas-** [comment]
@sahanDissanayake Could you provide a use case or something more to go on?

**Comment by danielsharvey** [comment]
I'm using Sails 1.0.2 and this configuration works:

```
module.exports.session = {
    secret: '<>',
    ivlength: 16,
    adapter: 'connect-mysql',
    pool: true,
    config: sessionConnectionDetails,
    table: 'sessions',
    cleanup: true,
  }
```

**Comment by jas-** [comment]
@danielsharvey Thanks for responding to this with a working config. As such and with the lack of responses from the OP I am going to mark this closed.
