### ISSUE TITLE
Does this work with Express 4?

### ISSUE THREAD

**Issue by thomasbaldwin** [nlf/connect-mysql#29]
I've been having trouble getting this to work with Express 4.12.3, and then I noticed there hasn't been any updates in over a year. Which got me thinking, does this library support Express 4?

**Comment by thomasbaldwin** [comment]
Nvm I figured it out and saw there was already a post regarding this that had been closed. Cheers

**Comment by jas-** [comment]
@thomasbaldwin Thanks for reporting this. `v2.1.3` addresses this discrepancy in the documentation as you had already found.
