### ISSUE TITLE
great start point but get / set is called too often

### ISSUE THREAD

**Issue by GoNode5** [nlf/connect-mysql#4]
Great starting point, but when I put a simple console in the get / set functions its
called very often, even on a simple login page... Imaging if there would be 100 users..
Is this normal behavior?

connect mysql GET:     ChZVe-srbodUH1s7xrjAFu1I
start login...
connect mysql    SET:  ChZVe-srbodUH1s7xrjAFu1I
_session.js_**_unmodified session
connect mysql GET:     ChZVe-srbodUH1s7xrjAFu1I
connect mysql GET:     ChZVe-srbodUH1s7xrjAFu1I
connect mysql    SET:  ChZVe-srbodUH1s7xrjAFu1I
connect mysql GET:     ChZVe-srbodUH1s7xrjAFu1I
connect mysql    SET:  ChZVe-srbodUH1s7xrjAFu1I
connect mysql    SET:  ChZVe-srbodUH1s7xrjAFu1I
*session.js**__unmodified session
*session.js_**_unmodified session
*session.js**__unmodified session
connect mysql GET:     ChZVe-srbodUH1s7xrjAFu1I
connect mysql    SET:  ChZVe-srbodUH1s7xrjAFu1I
*session.js_***unmodified session

**Comment by jas-** [comment]
@GoNode5 I am marking this resolved as it is by design unless you can provide a use case that is breaking the middleware.
