### ISSUE TITLE
JSON.parse() exceptions with existing session data (pre v2.2)

### ISSUE THREAD

**Issue by danielsharvey** [nlf/connect-mysql#47]
When the `sessions` table contains sessions data saved prior to the update, the `JSON.parse()` throws an exception which breaks sessions restoration.

I suggest these exceptions should be caught and the session 'reset', perhaps with a warning.

This specific occurrence is a transitional issue but the exception should be handled in some manner.

Thoughts?

**Comment by jas-** [comment]
I agree, do you perhaps have a patch or pr to implement?

**Comment by danielsharvey** [comment]
Yes, will do.
