### ISSUE TITLE
Sequelize

### ISSUE THREAD

**Issue by ThiagoMiranda** [nlf/connect-mysql#6]
I'm passing the Sequelize object to the client option. The queries works but the Sequelize uses a different event handler ( with success and error chained ). Do you plan to support it?

**Comment by jas-** [comment]
@ThiagoMiranda There currently are a couple session store's available that should suite your needs; [connect-sequelize](https://www.npmjs.com/package/connect-sequelize) & [express-sequelize](https://www.npmjs.com/package/express-sequelize).

This is a mysql specific session store. Thanks!
